"use client";

import React, { useState } from "react";
import {
  SandpackCodeEditor,
  SandpackConsole,
  SandpackFileExplorer,
  SandpackLayout,
  SandpackPreview,
  SandpackProvider,
} from "@codesandbox/sandpack-react";
import Lookup from "@/data/Lookup";
import { Loader2Icon, Download, Share2, LayoutPanelTop, PanelsTopLeft, Terminal } from "lucide-react";
import { Button } from "../ui/button";
import { useCodeGeneration } from "@/hooks/useCodeGeneration";

const CodeView = ({ layoutMode, setLayoutMode }) => {
  const { isGenerating, contextFiles, downloadProject, sharePreview } =
    useCodeGeneration();
  const [showConsole, setShowConsole] = useState(false);

  // Prefer context files (loaded from DB or generated by AI); fall back to default template
  const sandpackFiles = contextFiles || Lookup.DEFAULT_FILE;
  
  const isFloating = layoutMode === "floating";

  return (
    <div className="w-full flex-1 flex flex-col min-w-0">
      {/* Toolbar */}
      <div className="flex justify-end pr-2 pt-2 gap-2 mb-2">
        <Button variant="outline" size="sm" onClick={sharePreview}>
          <Share2 className="w-4 h-4 mr-2" />
          Share
        </Button>
        <Button
          variant="outline"
          size="sm"
          onClick={() => downloadProject(sandpackFiles)}
        >
          <Download className="w-4 h-4 mr-2" />
          Download
        </Button>
        <Button
          variant={showConsole ? "default" : "outline"}
          size="sm"
          onClick={() => setShowConsole((v) => !v)}
          title="Toggle Console"
        >
          <Terminal className="w-4 h-4 mr-2" />
          Console
        </Button>
        <Button
          variant="outline"
          size="sm"
          onClick={() => setLayoutMode(isFloating ? "split" : "floating")}
          title={isFloating ? "Switch to Split View" : "Switch to Floating View"}
        >
          {isFloating ? <PanelsTopLeft className="w-4 h-4 mr-2" /> : <LayoutPanelTop className="w-4 h-4 mr-2" />}
          {isFloating ? "Split" : "Float"}
        </Button>
      </div>

      {/* Sandpack */}
      <div className="relative flex-1 rounded-xl overflow-hidden shadow-sm border border-gray-200 dark:border-gray-800">
        {isGenerating && (
          <div className="absolute inset-0 z-10 flex flex-col items-center justify-center bg-black/60 rounded-md gap-3">
            <Loader2Icon className="animate-spin w-8 h-8 text-white" />
            <p className="text-white text-sm">Generating code...</p>
          </div>
        )}

        <SandpackProvider
          files={sandpackFiles}
          theme="dark"
          template="react"
          customSetup={{
            dependencies: { ...Lookup.DEPENDANCY },
          }}
          options={{
            externalResources: ["https://cdn.tailwindcss.com"],
          }}
        >
          <SandpackLayout className="!border-none">
            <SandpackFileExplorer style={{ height: isFloating ? "90vh" : "60vh" }} />
            <SandpackCodeEditor
              closableTabs
              showTabs
              style={{ height: isFloating ? "90vh" : "60vh" }}
            />
            <SandpackPreview style={{ height: isFloating ? "90vh" : "60vh" }} />
          </SandpackLayout>
          {showConsole && (
            <div className="border-t border-gray-200 dark:border-gray-700">
              <SandpackConsole style={{ height: "160px" }} />
            </div>
          )}
        </SandpackProvider>
      </div>
    </div>
  );
};

export default CodeView;
