import { ThemeProvider } from "@/providers/theme-provider";
import "./globals.css";
import { Header } from "@/components/Navbar/Header";
import { GlobalProvidor } from "@/providers/GlobalProvidor";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>
        <GlobalProvidor>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Header />
            {children}
          </ThemeProvider>
        </GlobalProvidor>
      </body>
    </html>
  );
}
